repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.750
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --warn-unused-configs, --warn-return-any, --warn-redundant-casts, --warn-no-return, --warn-unreachable]
-   repo: https://github.com/gvanderest/pylama-pre-commit
    rev: 0.1.2
    hooks:
    - id: pylama
-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    - id: bandit
